### ISSUE TITLE
After typing few words it starts at same line and overwrite it. 

### ISSUE THREAD

**Issue by 1heking** [noob-hackers/T-LOAD#1]
Hey Nitro you do a great job by building this. But after typing some words in same line it starts overwrite at same line and when we delete that words it removes everything. Can you please fix it. 
![Screenshot_2020-02-13-12-08-13-558_com termux](https://user-images.githubusercontent.com/60523039/74408121-98c00b80-4e59-11ea-9d70-d02b88ee2840.jpg)

**Comment by noob-hackers** [comment]
you can outzoom screen in this case it will be fixed

**Comment by hanu100** [comment]
How to delete this
