### ISSUE TITLE
How to change the interface of termux 

### ISSUE THREAD

**Issue by ETERNAL-VENOM** [noob-hackers/T-LOAD#6]
As you change the icon and image or ASCII desgin in termux per each video on YouTube 
![20200705_040255](https://user-images.githubusercontent.com/67844299/86521960-b75c8880-be74-11ea-860d-0e3e03384d63.jpg)
![20200705_040342](https://user-images.githubusercontent.com/67844299/86521965-c3e0e100-be74-11ea-9a77-7a13b1e0cf11.jpg)

And I created my own using crazy banner tool like this 
![20200705_040411](https://user-images.githubusercontent.com/67844299/86521976-e70b9080-be74-11ea-8ad2-f8e1a320a350.jpg)

And I'm really requesting you to do a video on how to make a new ASCII desgin from a photo and how to keep it as banner for termux and tell me how to create a color changing banner for termux

And make a tool for this

**Comment by Alphakataki** [comment]
Do you got how to do that
